#############################################################################
# Makefile for building: openBrf
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  openBrf.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile openBrf.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -isystem ./vcglib -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Ilib3ds-1.3.0 -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Itmp -Itmp -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = openBrf1.0.0
DISTDIR = /home/sasa/Desktop/mywork/openbrf/.tmp/openBrf1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lGLU /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		glwidgets.cpp \
		saveLoad.cpp \
		brfMesh.cpp \
		brfData.cpp \
		selector.cpp \
		tablemodel.cpp \
		brfShader.cpp \
		brfTexture.cpp \
		brfMaterial.cpp \
		brfSkeleton.cpp \
		brfAnimation.cpp \
		brfBody.cpp \
		guipanel.cpp \
		vcgmesh.cpp \
		askBoneDialog.cpp \
		vcglib/wrap/ply/plylib.cpp \
		vcglib/wrap/dae/xmldocumentmanaging.cpp \
		ioSMD.cpp \
		askSkelDialog.cpp \
		askTexturenameDialog.cpp \
		askFlagsDialog.cpp \
		iniData.cpp \
		ioOBJ.cpp \
		askModErrorDialog.cpp \
		ioMB.cpp \
		askTransformDialog.cpp \
		askCreaseDialog.cpp \
		main_info.cpp \
		main_create.cpp \
		main_ImpExp.cpp \
		brfHitBox.cpp \
		ioMD3.cpp \
		platform.cpp \
		askNewUiPictureDialog.cpp \
		askSelectBrfDialog.cpp \
		askUnrefTextureDialog.cpp \
		askIntervalDialog.cpp \
		askHueSatBriDialog.cpp \
		askLodOptionsDialog.cpp \
		askUvTransformDialog.cpp \
		askSkelPairDialog.cpp \
		askColorDialog.cpp \
		myselectionmodel.cpp qrc_resource.cpp \
		tmp/moc_mainwindow.cpp \
		tmp/moc_glwidgets.cpp \
		tmp/moc_selector.cpp \
		tmp/moc_tablemodel.cpp \
		tmp/moc_guipanel.cpp \
		tmp/moc_askBoneDialog.cpp \
		tmp/moc_askSkelDialog.cpp \
		tmp/moc_askTexturenameDialog.cpp \
		tmp/moc_askFlagsDialog.cpp \
		tmp/moc_askModErrorDialog.cpp \
		tmp/moc_askTransformDialog.cpp \
		tmp/moc_askCreaseDialog.cpp \
		tmp/moc_askNewUiPictureDialog.cpp \
		tmp/moc_askSelectBrfDialog.cpp \
		tmp/moc_askUnrefTextureDialog.cpp \
		tmp/moc_askIntervalDialog.cpp \
		tmp/moc_askHueSatBriDialog.cpp \
		tmp/moc_askLodOptionsDialog.cpp \
		tmp/moc_askUvTransformDialog.cpp \
		tmp/moc_askSkelPairDialog.cpp \
		tmp/moc_askColorDialog.cpp \
		tmp/moc_myselectionmodel.cpp
OBJECTS       = main.o \
		mainwindow.o \
		glwidgets.o \
		saveLoad.o \
		brfMesh.o \
		brfData.o \
		selector.o \
		tablemodel.o \
		brfShader.o \
		brfTexture.o \
		brfMaterial.o \
		brfSkeleton.o \
		brfAnimation.o \
		brfBody.o \
		guipanel.o \
		vcgmesh.o \
		askBoneDialog.o \
		plylib.o \
		xmldocumentmanaging.o \
		ioSMD.o \
		askSkelDialog.o \
		askTexturenameDialog.o \
		askFlagsDialog.o \
		iniData.o \
		ioOBJ.o \
		askModErrorDialog.o \
		ioMB.o \
		askTransformDialog.o \
		askCreaseDialog.o \
		main_info.o \
		main_create.o \
		main_ImpExp.o \
		brfHitBox.o \
		ioMD3.o \
		platform.o \
		askNewUiPictureDialog.o \
		askSelectBrfDialog.o \
		askUnrefTextureDialog.o \
		askIntervalDialog.o \
		askHueSatBriDialog.o \
		askLodOptionsDialog.o \
		askUvTransformDialog.o \
		askSkelPairDialog.o \
		askColorDialog.o \
		myselectionmodel.o \
		qrc_resource.o \
		moc_mainwindow.o \
		moc_glwidgets.o \
		moc_selector.o \
		moc_tablemodel.o \
		moc_guipanel.o \
		moc_askBoneDialog.o \
		moc_askSkelDialog.o \
		moc_askTexturenameDialog.o \
		moc_askFlagsDialog.o \
		moc_askModErrorDialog.o \
		moc_askTransformDialog.o \
		moc_askCreaseDialog.o \
		moc_askNewUiPictureDialog.o \
		moc_askSelectBrfDialog.o \
		moc_askUnrefTextureDialog.o \
		moc_askIntervalDialog.o \
		moc_askHueSatBriDialog.o \
		moc_askLodOptionsDialog.o \
		moc_askUvTransformDialog.o \
		moc_askSkelPairDialog.o \
		moc_askColorDialog.o \
		moc_myselectionmodel.o
DIST          = translations/openbrf_de.ts \
		translations/openbrf_en.ts \
		translations/openbrf_es.ts \
		translations/openbrf_zh.ts \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		openBrf.pro mainwindow.h \
		glwidgets.h \
		saveLoad.h \
		brfMesh.h \
		brfData.h \
		selector.h \
		tablemodel.h \
		brfShader.h \
		brfTexture.h \
		brfToken.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		guipanel.h \
		vcgmesh.h \
		vcgExport.h \
		vcgImport.h \
		askBoneDialog.h \
		ioSMD.h \
		askSkelDialog.h \
		askTexturenameDialog.h \
		askFlagsDialog.h \
		iniData.h \
		askModErrorDialog.h \
		ioMB.h \
		askTransformDialog.h \
		bindTexturePatch.h \
		ddsData.h \
		askCreaseDialog.h \
		ioOBJ.h \
		ioMD3.h \
		askNewUiPictureDialog.h \
		askSelectBrfDialog.h \
		askUnrefTextureDialog.h \
		askIntervalDialog.h \
		askHueSatBriDialog.h \
		askLodOptionsDialog.h \
		askUvTransformDialog.h \
		askSkelPairDialog.h \
		askColorDialog.h \
		carryPosition.h \
		myselectionmodel.h main.cpp \
		mainwindow.cpp \
		glwidgets.cpp \
		saveLoad.cpp \
		brfMesh.cpp \
		brfData.cpp \
		selector.cpp \
		tablemodel.cpp \
		brfShader.cpp \
		brfTexture.cpp \
		brfMaterial.cpp \
		brfSkeleton.cpp \
		brfAnimation.cpp \
		brfBody.cpp \
		guipanel.cpp \
		vcgmesh.cpp \
		askBoneDialog.cpp \
		vcglib/wrap/ply/plylib.cpp \
		vcglib/wrap/dae/xmldocumentmanaging.cpp \
		ioSMD.cpp \
		askSkelDialog.cpp \
		askTexturenameDialog.cpp \
		askFlagsDialog.cpp \
		iniData.cpp \
		ioOBJ.cpp \
		askModErrorDialog.cpp \
		ioMB.cpp \
		askTransformDialog.cpp \
		askCreaseDialog.cpp \
		main_info.cpp \
		main_create.cpp \
		main_ImpExp.cpp \
		brfHitBox.cpp \
		ioMD3.cpp \
		platform.cpp \
		askNewUiPictureDialog.cpp \
		askSelectBrfDialog.cpp \
		askUnrefTextureDialog.cpp \
		askIntervalDialog.cpp \
		askHueSatBriDialog.cpp \
		askLodOptionsDialog.cpp \
		askUvTransformDialog.cpp \
		askSkelPairDialog.cpp \
		askColorDialog.cpp \
		myselectionmodel.cpp
QMAKE_TARGET  = openBrf
DESTDIR       = 
TARGET        = openBrf


first: all
####### Build rules

openBrf: tmp/ui_guipanel.h tmp/ui_askBoneDialog.h tmp/ui_askSkelDialog.h tmp/ui_askTexturenameDialog.h tmp/ui_askFlagsDialog.h tmp/ui_askModErrorDialog.h tmp/ui_askTransformDialog.h tmp/ui_askCreaseDialog.h tmp/ui_mainwindow.h tmp/ui_askNewUiPictureDialog.h tmp/ui_askSelectBrfDialog.h tmp/ui_askUnrefTextureDialog.h tmp/ui_askIntervalDialog.h tmp/ui_askHueSatBriDialog.h tmp/ui_askLodOptionsDialog.h tmp/ui_askUvTransformDialog.h tmp/ui_askSkelPairDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: openBrf.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		openBrf.pro \
		resource.qrc
	$(QMAKE) -o Makefile openBrf.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
openBrf.pro:
resource.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile openBrf.pro

qmake_all: FORCE


all: Makefile openBrf

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resource.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h glwidgets.h saveLoad.h brfMesh.h brfData.h selector.h tablemodel.h brfShader.h brfTexture.h brfToken.h brfMaterial.h brfSkeleton.h brfAnimation.h brfBody.h guipanel.h vcgmesh.h vcgExport.h vcgImport.h askBoneDialog.h ioSMD.h askSkelDialog.h askTexturenameDialog.h askFlagsDialog.h iniData.h askModErrorDialog.h ioMB.h askTransformDialog.h bindTexturePatch.h ddsData.h askCreaseDialog.h ioOBJ.h ioMD3.h askNewUiPictureDialog.h askSelectBrfDialog.h askUnrefTextureDialog.h askIntervalDialog.h askHueSatBriDialog.h askLodOptionsDialog.h askUvTransformDialog.h askSkelPairDialog.h askColorDialog.h carryPosition.h myselectionmodel.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp glwidgets.cpp saveLoad.cpp brfMesh.cpp brfData.cpp selector.cpp tablemodel.cpp brfShader.cpp brfTexture.cpp brfMaterial.cpp brfSkeleton.cpp brfAnimation.cpp brfBody.cpp guipanel.cpp vcgmesh.cpp askBoneDialog.cpp vcglib/wrap/ply/plylib.cpp vcglib/wrap/dae/xmldocumentmanaging.cpp ioSMD.cpp askSkelDialog.cpp askTexturenameDialog.cpp askFlagsDialog.cpp iniData.cpp ioOBJ.cpp askModErrorDialog.cpp ioMB.cpp askTransformDialog.cpp askCreaseDialog.cpp main_info.cpp main_create.cpp main_ImpExp.cpp brfHitBox.cpp ioMD3.cpp platform.cpp askNewUiPictureDialog.cpp askSelectBrfDialog.cpp askUnrefTextureDialog.cpp askIntervalDialog.cpp askHueSatBriDialog.cpp askLodOptionsDialog.cpp askUvTransformDialog.cpp askSkelPairDialog.cpp askColorDialog.cpp myselectionmodel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents guipanel.ui askBoneDialog.ui askSkelDialog.ui askTexturenameDialog.ui askFlagsDialog.ui askModErrorDialog.ui askTransformDialog.ui askCreaseDialog.ui mainwindow.ui askNewUiPictureDialog.ui askSelectBrfDialog.ui askUnrefTextureDialog.ui askIntervalDialog.ui askHueSatBriDialog.ui askLodOptionsDialog.ui askUvTransformDialog.ui askSkelPairDialog.ui $(DISTDIR)/
	$(COPY_FILE) --parents translations/openbrf_zh.ts translations/openbrf_en.ts translations/openbrf_es.ts translations/openbrf_de.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		/usr/lib/qt5/bin/rcc \
		femininizer.morpher \
		carry_positions.txt \
		openBrf.ico \
		shaders/bump_vertex.cpp \
		shaders/bump_fragment.cpp \
		shaders/iron_fragment.cpp \
		icons/ico_mid.png \
		icons/ico_left.png \
		icons/ico_right.png \
		translations/openbrf_es.qm \
		translations/qt_zh_CN.qm \
		translations/openbrf_de.qm \
		translations/openbrf_zh.qm \
		translations/qt_es.qm
	/usr/lib/qt5/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_moc_predefs_make_all: tmp/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) tmp/moc_predefs.h
tmp/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++0x -isystem ./vcglib -O2 -Wall -Wextra -dM -E -o tmp/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: tmp/moc_mainwindow.cpp tmp/moc_glwidgets.cpp tmp/moc_selector.cpp tmp/moc_tablemodel.cpp tmp/moc_guipanel.cpp tmp/moc_askBoneDialog.cpp tmp/moc_askSkelDialog.cpp tmp/moc_askTexturenameDialog.cpp tmp/moc_askFlagsDialog.cpp tmp/moc_askModErrorDialog.cpp tmp/moc_askTransformDialog.cpp tmp/moc_askCreaseDialog.cpp tmp/moc_askNewUiPictureDialog.cpp tmp/moc_askSelectBrfDialog.cpp tmp/moc_askUnrefTextureDialog.cpp tmp/moc_askIntervalDialog.cpp tmp/moc_askHueSatBriDialog.cpp tmp/moc_askLodOptionsDialog.cpp tmp/moc_askUvTransformDialog.cpp tmp/moc_askSkelPairDialog.cpp tmp/moc_askColorDialog.cpp tmp/moc_myselectionmodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc_mainwindow.cpp tmp/moc_glwidgets.cpp tmp/moc_selector.cpp tmp/moc_tablemodel.cpp tmp/moc_guipanel.cpp tmp/moc_askBoneDialog.cpp tmp/moc_askSkelDialog.cpp tmp/moc_askTexturenameDialog.cpp tmp/moc_askFlagsDialog.cpp tmp/moc_askModErrorDialog.cpp tmp/moc_askTransformDialog.cpp tmp/moc_askCreaseDialog.cpp tmp/moc_askNewUiPictureDialog.cpp tmp/moc_askSelectBrfDialog.cpp tmp/moc_askUnrefTextureDialog.cpp tmp/moc_askIntervalDialog.cpp tmp/moc_askHueSatBriDialog.cpp tmp/moc_askLodOptionsDialog.cpp tmp/moc_askUvTransformDialog.cpp tmp/moc_askSkelPairDialog.cpp tmp/moc_askColorDialog.cpp tmp/moc_myselectionmodel.cpp
tmp/moc_mainwindow.cpp: mainwindow.h \
		brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		iniData.h \
		glwidgets.h \
		ddsData.h \
		selector.h \
		guipanel.h \
		brfHitBox.h \
		carryPosition.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o tmp/moc_mainwindow.cpp

tmp/moc_glwidgets.cpp: glwidgets.h \
		brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		iniData.h \
		ddsData.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include glwidgets.h -o tmp/moc_glwidgets.cpp

tmp/moc_selector.cpp: selector.h \
		brfToken.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include selector.h -o tmp/moc_selector.cpp

tmp/moc_tablemodel.cpp: tablemodel.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tablemodel.h -o tmp/moc_tablemodel.cpp

tmp/moc_guipanel.cpp: guipanel.h \
		ddsData.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include guipanel.h -o tmp/moc_guipanel.cpp

tmp/moc_askBoneDialog.cpp: askBoneDialog.h \
		brfSkeleton.h \
		brfToken.h \
		carryPosition.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askBoneDialog.h -o tmp/moc_askBoneDialog.cpp

tmp/moc_askSkelDialog.cpp: askSkelDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askSkelDialog.h -o tmp/moc_askSkelDialog.cpp

tmp/moc_askTexturenameDialog.cpp: askTexturenameDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askTexturenameDialog.h -o tmp/moc_askTexturenameDialog.cpp

tmp/moc_askFlagsDialog.cpp: askFlagsDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askFlagsDialog.h -o tmp/moc_askFlagsDialog.cpp

tmp/moc_askModErrorDialog.cpp: askModErrorDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askModErrorDialog.h -o tmp/moc_askModErrorDialog.cpp

tmp/moc_askTransformDialog.cpp: askTransformDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askTransformDialog.h -o tmp/moc_askTransformDialog.cpp

tmp/moc_askCreaseDialog.cpp: askCreaseDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askCreaseDialog.h -o tmp/moc_askCreaseDialog.cpp

tmp/moc_askNewUiPictureDialog.cpp: askNewUiPictureDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askNewUiPictureDialog.h -o tmp/moc_askNewUiPictureDialog.cpp

tmp/moc_askSelectBrfDialog.cpp: askSelectBrfDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askSelectBrfDialog.h -o tmp/moc_askSelectBrfDialog.cpp

tmp/moc_askUnrefTextureDialog.cpp: askUnrefTextureDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askUnrefTextureDialog.h -o tmp/moc_askUnrefTextureDialog.cpp

tmp/moc_askIntervalDialog.cpp: askIntervalDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askIntervalDialog.h -o tmp/moc_askIntervalDialog.cpp

tmp/moc_askHueSatBriDialog.cpp: askHueSatBriDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askHueSatBriDialog.h -o tmp/moc_askHueSatBriDialog.cpp

tmp/moc_askLodOptionsDialog.cpp: askLodOptionsDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askLodOptionsDialog.h -o tmp/moc_askLodOptionsDialog.cpp

tmp/moc_askUvTransformDialog.cpp: askUvTransformDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askUvTransformDialog.h -o tmp/moc_askUvTransformDialog.cpp

tmp/moc_askSkelPairDialog.cpp: askSkelPairDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askSkelPairDialog.h -o tmp/moc_askSkelPairDialog.cpp

tmp/moc_askColorDialog.cpp: askColorDialog.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include askColorDialog.h -o tmp/moc_askColorDialog.cpp

tmp/moc_myselectionmodel.cpp: myselectionmodel.h \
		tmp/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/sasa/Desktop/mywork/openbrf/tmp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/sasa/Desktop/mywork/openbrf -I/home/sasa/Desktop/mywork/openbrf/lib3ds-1.3.0 -I/home/sasa/Desktop/mywork/openbrf -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include myselectionmodel.h -o tmp/moc_myselectionmodel.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: tmp/ui_guipanel.h tmp/ui_askBoneDialog.h tmp/ui_askSkelDialog.h tmp/ui_askTexturenameDialog.h tmp/ui_askFlagsDialog.h tmp/ui_askModErrorDialog.h tmp/ui_askTransformDialog.h tmp/ui_askCreaseDialog.h tmp/ui_mainwindow.h tmp/ui_askNewUiPictureDialog.h tmp/ui_askSelectBrfDialog.h tmp/ui_askUnrefTextureDialog.h tmp/ui_askIntervalDialog.h tmp/ui_askHueSatBriDialog.h tmp/ui_askLodOptionsDialog.h tmp/ui_askUvTransformDialog.h tmp/ui_askSkelPairDialog.h
compiler_uic_clean:
	-$(DEL_FILE) tmp/ui_guipanel.h tmp/ui_askBoneDialog.h tmp/ui_askSkelDialog.h tmp/ui_askTexturenameDialog.h tmp/ui_askFlagsDialog.h tmp/ui_askModErrorDialog.h tmp/ui_askTransformDialog.h tmp/ui_askCreaseDialog.h tmp/ui_mainwindow.h tmp/ui_askNewUiPictureDialog.h tmp/ui_askSelectBrfDialog.h tmp/ui_askUnrefTextureDialog.h tmp/ui_askIntervalDialog.h tmp/ui_askHueSatBriDialog.h tmp/ui_askLodOptionsDialog.h tmp/ui_askUvTransformDialog.h tmp/ui_askSkelPairDialog.h
tmp/ui_guipanel.h: guipanel.ui \
		/usr/lib/qt5/bin/uic \
		tablemodel.h
	/usr/lib/qt5/bin/uic guipanel.ui -o tmp/ui_guipanel.h

tmp/ui_askBoneDialog.h: askBoneDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askBoneDialog.ui -o tmp/ui_askBoneDialog.h

tmp/ui_askSkelDialog.h: askSkelDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askSkelDialog.ui -o tmp/ui_askSkelDialog.h

tmp/ui_askTexturenameDialog.h: askTexturenameDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askTexturenameDialog.ui -o tmp/ui_askTexturenameDialog.h

tmp/ui_askFlagsDialog.h: askFlagsDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askFlagsDialog.ui -o tmp/ui_askFlagsDialog.h

tmp/ui_askModErrorDialog.h: askModErrorDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askModErrorDialog.ui -o tmp/ui_askModErrorDialog.h

tmp/ui_askTransformDialog.h: askTransformDialog.ui \
		/usr/lib/qt5/bin/uic \
		tablemodel.h
	/usr/lib/qt5/bin/uic askTransformDialog.ui -o tmp/ui_askTransformDialog.h

tmp/ui_askCreaseDialog.h: askCreaseDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askCreaseDialog.ui -o tmp/ui_askCreaseDialog.h

tmp/ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o tmp/ui_mainwindow.h

tmp/ui_askNewUiPictureDialog.h: askNewUiPictureDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askNewUiPictureDialog.ui -o tmp/ui_askNewUiPictureDialog.h

tmp/ui_askSelectBrfDialog.h: askSelectBrfDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askSelectBrfDialog.ui -o tmp/ui_askSelectBrfDialog.h

tmp/ui_askUnrefTextureDialog.h: askUnrefTextureDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askUnrefTextureDialog.ui -o tmp/ui_askUnrefTextureDialog.h

tmp/ui_askIntervalDialog.h: askIntervalDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askIntervalDialog.ui -o tmp/ui_askIntervalDialog.h

tmp/ui_askHueSatBriDialog.h: askHueSatBriDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askHueSatBriDialog.ui -o tmp/ui_askHueSatBriDialog.h

tmp/ui_askLodOptionsDialog.h: askLodOptionsDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askLodOptionsDialog.ui -o tmp/ui_askLodOptionsDialog.h

tmp/ui_askUvTransformDialog.h: askUvTransformDialog.ui \
		/usr/lib/qt5/bin/uic \
		tablemodel.h
	/usr/lib/qt5/bin/uic askUvTransformDialog.ui -o tmp/ui_askUvTransformDialog.h

tmp/ui_askSkelPairDialog.h: askSkelPairDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic askSkelPairDialog.ui -o tmp/ui_askSkelPairDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		iniData.h \
		glwidgets.h \
		ddsData.h \
		selector.h \
		guipanel.h \
		brfHitBox.h \
		carryPosition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		glwidgets.h \
		iniData.h \
		ddsData.h \
		selector.h \
		mainwindow.h \
		guipanel.h \
		brfHitBox.h \
		carryPosition.h \
		tmp/ui_mainwindow.h \
		tmp/ui_guipanel.h \
		askBoneDialog.h \
		askSkelDialog.h \
		askTexturenameDialog.h \
		askModErrorDialog.h \
		askTransformDialog.h \
		askUvTransformDialog.h \
		askCreaseDialog.h \
		askNewUiPictureDialog.h \
		askUnrefTextureDialog.h \
		askSelectBrfDialog.h \
		askSkelPairDialog.h \
		askIntervalDialog.h \
		askHueSatBriDialog.h \
		askLodOptionsDialog.h \
		askColorDialog.h \
		askFlagsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

glwidgets.o: glwidgets.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		glwidgets.h \
		iniData.h \
		ddsData.h \
		bindTexturePatch.h \
		platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidgets.o glwidgets.cpp

saveLoad.o: saveLoad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saveLoad.o saveLoad.cpp

brfMesh.o: brfMesh.cpp brfMesh.h \
		brfToken.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		carryPosition.h \
		saveLoad.h \
		platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfMesh.o brfMesh.cpp

brfData.o: brfData.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		saveLoad.h \
		platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfData.o brfData.cpp

selector.o: selector.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		selector.h \
		iniData.h \
		tablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selector.o selector.cpp

tablemodel.o: tablemodel.cpp tablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablemodel.o tablemodel.cpp

brfShader.o: brfShader.cpp brfShader.h \
		brfToken.h \
		saveLoad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfShader.o brfShader.cpp

brfTexture.o: brfTexture.cpp saveLoad.h \
		brfTexture.h \
		brfToken.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfTexture.o brfTexture.cpp

brfMaterial.o: brfMaterial.cpp saveLoad.h \
		brfMaterial.h \
		brfToken.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfMaterial.o brfMaterial.cpp

brfSkeleton.o: brfSkeleton.cpp brfSkeleton.h \
		brfToken.h \
		brfAnimation.h \
		brfMesh.h \
		brfBody.h \
		saveLoad.h \
		platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfSkeleton.o brfSkeleton.cpp

brfAnimation.o: brfAnimation.cpp saveLoad.h \
		platform.h \
		brfSkeleton.h \
		brfToken.h \
		brfAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfAnimation.o brfAnimation.cpp

brfBody.o: brfBody.cpp brfBody.h \
		brfToken.h \
		saveLoad.h \
		platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfBody.o brfBody.cpp

guipanel.o: guipanel.cpp guipanel.h \
		ddsData.h \
		tmp/ui_guipanel.h \
		brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		iniData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guipanel.o guipanel.cpp

vcgmesh.o: vcgmesh.cpp vcgExport.h \
		vcgImport.h \
		vcgmesh.h \
		brfBody.h \
		brfToken.h \
		brfMesh.h \
		brfSkeleton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vcgmesh.o vcgmesh.cpp

askBoneDialog.o: askBoneDialog.cpp askBoneDialog.h \
		brfSkeleton.h \
		brfToken.h \
		carryPosition.h \
		tmp/ui_askBoneDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askBoneDialog.o askBoneDialog.cpp

plylib.o: vcglib/wrap/ply/plylib.cpp vcglib/wrap/ply/plylib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plylib.o vcglib/wrap/ply/plylib.cpp

xmldocumentmanaging.o: vcglib/wrap/dae/xmldocumentmanaging.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmldocumentmanaging.o vcglib/wrap/dae/xmldocumentmanaging.cpp

ioSMD.o: ioSMD.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		platform.h \
		ioSMD.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioSMD.o ioSMD.cpp

askSkelDialog.o: askSkelDialog.cpp askSkelDialog.h \
		tmp/ui_askSkelDialog.h \
		brfSkeleton.h \
		brfToken.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askSkelDialog.o askSkelDialog.cpp

askTexturenameDialog.o: askTexturenameDialog.cpp askTexturenameDialog.h \
		tmp/ui_askTexturenameDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askTexturenameDialog.o askTexturenameDialog.cpp

askFlagsDialog.o: askFlagsDialog.cpp askFlagsDialog.h \
		tmp/ui_askFlagsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askFlagsDialog.o askFlagsDialog.cpp

iniData.o: iniData.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		iniData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iniData.o iniData.cpp

ioOBJ.o: ioOBJ.cpp brfMesh.h \
		brfToken.h \
		brfBody.h \
		brfSkeleton.h \
		ioOBJ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioOBJ.o ioOBJ.cpp

askModErrorDialog.o: askModErrorDialog.cpp askModErrorDialog.h \
		tmp/ui_askModErrorDialog.h \
		brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		iniData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askModErrorDialog.o askModErrorDialog.cpp

ioMB.o: ioMB.cpp brfMesh.h \
		brfToken.h \
		brfSkeleton.h \
		brfAnimation.h \
		platform.h \
		ioMB.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioMB.o ioMB.cpp

askTransformDialog.o: askTransformDialog.cpp askTransformDialog.h \
		tmp/ui_askTransformDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askTransformDialog.o askTransformDialog.cpp

askCreaseDialog.o: askCreaseDialog.cpp askCreaseDialog.h \
		tmp/ui_askCreaseDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askCreaseDialog.o askCreaseDialog.cpp

main_info.o: main_info.cpp glwidgets.h \
		brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		iniData.h \
		ddsData.h \
		mainwindow.h \
		selector.h \
		guipanel.h \
		brfHitBox.h \
		carryPosition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_info.o main_info.cpp

main_create.o: main_create.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		glwidgets.h \
		iniData.h \
		ddsData.h \
		selector.h \
		mainwindow.h \
		guipanel.h \
		brfHitBox.h \
		carryPosition.h \
		tmp/ui_guipanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_create.o main_create.cpp

main_ImpExp.o: main_ImpExp.cpp brfData.h \
		brfToken.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h \
		brfBody.h \
		selector.h \
		mainwindow.h \
		iniData.h \
		glwidgets.h \
		ddsData.h \
		guipanel.h \
		brfHitBox.h \
		carryPosition.h \
		vcgmesh.h \
		ioSMD.h \
		ioMD3.h \
		ioMB.h \
		ioOBJ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_ImpExp.o main_ImpExp.cpp

brfHitBox.o: brfHitBox.cpp brfBody.h \
		brfToken.h \
		brfData.h \
		brfMesh.h \
		brfTexture.h \
		brfShader.h \
		brfMaterial.h \
		brfSkeleton.h \
		brfAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brfHitBox.o brfHitBox.cpp

ioMD3.o: ioMD3.cpp brfMesh.h \
		brfToken.h \
		ioMD3.h \
		saveLoad.h \
		platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ioMD3.o ioMD3.cpp

platform.o: platform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform.o platform.cpp

askNewUiPictureDialog.o: askNewUiPictureDialog.cpp askNewUiPictureDialog.h \
		tmp/ui_askNewUiPictureDialog.h \
		ddsData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askNewUiPictureDialog.o askNewUiPictureDialog.cpp

askSelectBrfDialog.o: askSelectBrfDialog.cpp askSelectBrfDialog.h \
		tmp/ui_askSelectBrfDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askSelectBrfDialog.o askSelectBrfDialog.cpp

askUnrefTextureDialog.o: askUnrefTextureDialog.cpp askUnrefTextureDialog.h \
		tmp/ui_askUnrefTextureDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askUnrefTextureDialog.o askUnrefTextureDialog.cpp

askIntervalDialog.o: askIntervalDialog.cpp askIntervalDialog.h \
		tmp/ui_askIntervalDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askIntervalDialog.o askIntervalDialog.cpp

askHueSatBriDialog.o: askHueSatBriDialog.cpp tmp/ui_askHueSatBriDialog.h \
		askHueSatBriDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askHueSatBriDialog.o askHueSatBriDialog.cpp

askLodOptionsDialog.o: askLodOptionsDialog.cpp askLodOptionsDialog.h \
		tmp/ui_askLodOptionsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askLodOptionsDialog.o askLodOptionsDialog.cpp

askUvTransformDialog.o: askUvTransformDialog.cpp askUvTransformDialog.h \
		tmp/ui_askUvTransformDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askUvTransformDialog.o askUvTransformDialog.cpp

askSkelPairDialog.o: askSkelPairDialog.cpp askSkelPairDialog.h \
		tmp/ui_askSkelPairDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askSkelPairDialog.o askSkelPairDialog.cpp

askColorDialog.o: askColorDialog.cpp askColorDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o askColorDialog.o askColorDialog.cpp

myselectionmodel.o: myselectionmodel.cpp myselectionmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myselectionmodel.o myselectionmodel.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

moc_mainwindow.o: tmp/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o tmp/moc_mainwindow.cpp

moc_glwidgets.o: tmp/moc_glwidgets.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidgets.o tmp/moc_glwidgets.cpp

moc_selector.o: tmp/moc_selector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selector.o tmp/moc_selector.cpp

moc_tablemodel.o: tmp/moc_tablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablemodel.o tmp/moc_tablemodel.cpp

moc_guipanel.o: tmp/moc_guipanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guipanel.o tmp/moc_guipanel.cpp

moc_askBoneDialog.o: tmp/moc_askBoneDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askBoneDialog.o tmp/moc_askBoneDialog.cpp

moc_askSkelDialog.o: tmp/moc_askSkelDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askSkelDialog.o tmp/moc_askSkelDialog.cpp

moc_askTexturenameDialog.o: tmp/moc_askTexturenameDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askTexturenameDialog.o tmp/moc_askTexturenameDialog.cpp

moc_askFlagsDialog.o: tmp/moc_askFlagsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askFlagsDialog.o tmp/moc_askFlagsDialog.cpp

moc_askModErrorDialog.o: tmp/moc_askModErrorDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askModErrorDialog.o tmp/moc_askModErrorDialog.cpp

moc_askTransformDialog.o: tmp/moc_askTransformDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askTransformDialog.o tmp/moc_askTransformDialog.cpp

moc_askCreaseDialog.o: tmp/moc_askCreaseDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askCreaseDialog.o tmp/moc_askCreaseDialog.cpp

moc_askNewUiPictureDialog.o: tmp/moc_askNewUiPictureDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askNewUiPictureDialog.o tmp/moc_askNewUiPictureDialog.cpp

moc_askSelectBrfDialog.o: tmp/moc_askSelectBrfDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askSelectBrfDialog.o tmp/moc_askSelectBrfDialog.cpp

moc_askUnrefTextureDialog.o: tmp/moc_askUnrefTextureDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askUnrefTextureDialog.o tmp/moc_askUnrefTextureDialog.cpp

moc_askIntervalDialog.o: tmp/moc_askIntervalDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askIntervalDialog.o tmp/moc_askIntervalDialog.cpp

moc_askHueSatBriDialog.o: tmp/moc_askHueSatBriDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askHueSatBriDialog.o tmp/moc_askHueSatBriDialog.cpp

moc_askLodOptionsDialog.o: tmp/moc_askLodOptionsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askLodOptionsDialog.o tmp/moc_askLodOptionsDialog.cpp

moc_askUvTransformDialog.o: tmp/moc_askUvTransformDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askUvTransformDialog.o tmp/moc_askUvTransformDialog.cpp

moc_askSkelPairDialog.o: tmp/moc_askSkelPairDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askSkelPairDialog.o tmp/moc_askSkelPairDialog.cpp

moc_askColorDialog.o: tmp/moc_askColorDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_askColorDialog.o tmp/moc_askColorDialog.cpp

moc_myselectionmodel.o: tmp/moc_myselectionmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myselectionmodel.o tmp/moc_myselectionmodel.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

